
export const ACHIEVEMENTS = [
    { id: 1,  name: "Scholar",          desc: "Complete your first 10 problems",       src: "academic.png",                       condition: (stats) => stats.totalSolved > 10 },
    { id: 2,  name: "Achiever",         desc: "Reach a 7-day streak",                   src: "achieve.png",                        condition: (stats) => stats.hard > 10000      },
    { id: 3,  name: "Champion",         desc: "Win your first contest",                  src: "achievement (1).png",              condition: (stats) => stats.totalSolved > 100      },
    { id: 4,  name: "Gold Badge",       desc: "Solve 100 problems",                     src: "achievement.png",                    condition: (stats) => stats.hard > 100000     },
    { id: 5,  name: "Top Performer",    desc: "Rank in the top 10% of a contest",       src: "award.png",                         condition: (stats) => stats.hard > 10000   },
    { id: 6,  name: "Badge Hunter",     desc: "Earn 5 different badges",                src: "badge.png",                          condition: (stats) => stats.hard > 100000  },
    { id: 7,  name: "Promoted",         desc: "Advance to the next rating tier",        src: "career-promotion.png",               condition: (stats) => stats.hard > 10000   },
    { id: 8,  name: "Climber",          desc: "Increase your rating by 200 points",     src: "climbing.png",                       condition: (stats) => stats.hard > 10000  },
    { id: 9,  name: "Collaborator",     desc: "Join a team contest",                    src: "collaborative-innovation-network.png", condition: (stats) => stats.hard > 100000   },
    { id: 10, name: "Diamond Coder",    desc: "Solve 500 problems",                     src: "diamond.png",                         condition: (stats) => stats.totalSolved > 500   },
    { id: 11, name: "Global Reach",     desc: "Compete in an international contest",    src: "global.png",                          condition: (stats) => stats.easy > 1000    },
    { id: 12, name: "Goal Getter I",    desc: "Complete a monthly challenge",           src: "goal (1).png",                        condition: (stats) => stats.medium > 500  },
    { id: 13, name: "Goal Getter II",   desc: "Complete 3 monthly challenges",          src: "goal (2).png",                        condition: (stats) => stats.medium > 100 },
    { id: 14, name: "On Target",        desc: "Hit your weekly goal 4 weeks in a row",  src: "goal.png",                            condition: (stats) => stats.easy > 500  },
    { id: 15, name: "High Quality",     desc: "Connect atleast 1 platform",src: "high-quality (1).png",                condition: (stats) => stats.platformsConnected.length >= 1  },
    { id: 16, name: "Perfectionist",    desc: "Solve 50 hard problems",                 src: "high-quality.png",                   condition: (stats) => stats.hard > 50 },
    { id: 17, name: "Top Ranked",       desc: "Connect all platforms",           src: "ranking.png",                        condition: (stats) => stats.platformsConnected.length = 4  },
    { id: 18, name: "Reach the Top",    desc: "Get a 30-day streak",                    src: "reach.png",                          condition: (stats) => stats.hard > 1 },
    { id: 19, name: "Success I",        desc: "Solve your first medium problem",         src: "success -2.png",                     condition: (stats) => stats.medium >= 1 },
    { id: 20, name: "Success II",       desc: "Solve your first hard problem",           src: "success (2).png",                    condition: (stats) => stats.hard >= 1  },
    { id: 21, name: "Victorious",       desc: "Solve all daily challenges in a month",  src: "success.png",                        condition: (stats) => stats.hard > 100000  },
    { id: 22, name: "Precision",        desc: "Submit a problem with O(n) optimally",   src: "target.png",                          condition: (stats) => stats.hard > 100000  },
    { id: 23, name: "Triumph",          desc: "Complete 200 Easy problems",     src: "triumph.png",                        condition: (stats) => stats.Easy > 200  },
    { id: 24, name: "Trophy Room",      desc: "Earn 10 total achievements",              src: "trophy.png",                         condition: (stats) => stats.hard > 600 },
];